-- Active: 1669920483595@@127.0.0.1@3306@trabajofinaldb

CREATE PROCEDURE REGISTRAR_USUARIO(NOM VARCHAR(
50), APE VARCHAR(80), EDAD_USER INT, CORREO_USER VARCHAR
(150), TAG_USER VARCHAR(16), PWD VARCHAR
(15), ID_PROV INT, TELEF VARCHAR(9)) BEGIN 
	INSERT INTO
	    usuarios(
	        NOMBRES,
	        APELLIDOS,
	        EDAD,
	        CORREO,
	        NOMBRE_USUARIO,
	        PASSWORD,
	        ID_PROVINCIA,
	        TELEFONO
	    )
	VALUES (
	        NOM,
	        APE,
	        EDAD_USER,
	        CORREO_USER,
	        TAG_USER,
	        PWD,
	        ID_PROV,
	        TELEF
	    );
END; 

CREATE PROCEDURE CONSULTAR_USUARIO(NOM_USER VARCHAR
(16), PWD VARCHAR(15)) BEGIN 
	SELECT *
from vista_login
WHERE
    `NOMBRE_USUARIO` = NOM_USER
    AND `PASSWORD` = PWD;
END;

CALL `CONSULTAR_USUARIO`('Fortalezawtf ', 'dddd');

CALL
    `REGISTRAR_USUARIO`(
        'Eliot Roy',
        'Aras Flores',
        18,
        'rampagecopilation@gmail.com',
        'F3123132or1',
        'ratmrssf',
        1,
        959596552
    );

CREATE PROCEDURE CONSULTAR_PAISES() BEGIN 
	SELECT DISTINCTROW
	    select_lugar.`ID_PAIS`,
		select_lugar.`NOMBRE_PAIS`
	FROM select_lugar;
END; 

CALL CONSULTAR_PAISES();

CREATE PROCEDURE CONSULTAR_DEPARTAMENTO(ID_DEPARTAMENTO INT) BEGIN 
	SELECT DISTINCTROW 
	    select_lugar.`ID_DEPARTAMENTO`,
	    select_lugar.`NOMBRE_DEPARTAMENTO`
	FROM select_lugar
	WHERE select_lugar.`ID_PAIS`= ID_DEPARTAMENTO;
END;

CALL `CONSULTAR_DEPARTAMENTO`(4);

CREATE PROCEDURE CONSULTAR_PROVINCIA(ID_PROVINCIA INT) 
BEGIN 
	SELECT
	    select_lugar.`ID_PROVINCIA`,
	    select_lugar.`NOMBRE_PROVINCIA`
	FROM select_lugar
	WHERE
	    select_lugar.`ID_DEPARTAMENTO` = ID_PROVINCIA;
END; 

CALL `CONSULTAR_PROVINCIA`(3);

CREATE PROCEDURE INFO_USUARIO(TAG_USER VARCHAR(50))
BEGIN
	SELECT * 
	FROM `usuarios` WHERE `NOMBRE_USUARIO` = TAG_USER;
END;

CALL `INFO_USUARIO`('Fortalezawtf2');

CREATE PROCEDURE CONSULTAR_TAG_USUARIO(TAG_USER VARCHAR(50))
BEGIN
	SELECT *
	FROM vista_login WHERE `NOMBRE_USUARIO` = TAG_USER;
END;

CALL CONSULTAR_TAG_USUARIO('Fortalezawtf2');